"use client";
import {useEffect,useRef,useState} from 'react';
import {createScene} from '@/lib/scene.mjs';
import {faceInput,clamp,safeFalUrl} from '@/lib/motion.mjs';
import {Slider} from '@/components/ui/slider';
import {ArrowUpRight,Camera,MousePointer2,Pause,Play,ScanFace,Sparkles,Download,RotateCcw} from 'lucide-react';
const presets=[{name:'Aurora bloom',tag:'01 / ORGANIC',color:'#baff6a'},{name:'Orbital silk',tag:'02 / ORBITAL',color:'#b29bff'},{name:'Solar current',tag:'03 / FLOW',color:'#ff9363'},{name:'Lightfield',tag:'04 / LIVING POSTER',color:'#91e6ff'}];
export default function Home(){
 const host=useRef<HTMLDivElement>(null), video=useRef<HTMLVideoElement>(null), api=useRef<any>(null), tracker=useRef<any>(null), stream=useRef<MediaStream|null>(null), trackFrame=useRef(0), generation=useRef(0);
 const center=useRef({x:.5,y:.5}),lastNose=useRef<{x:number,y:number}|null>(null);
 const input=useRef({x:0,y:0}), state=useRef({preset:0,speed:.6,spread:1,sensitivity:1.5,paused:false});
 const [preset,setPreset]=useState(0),[speed,setSpeed]=useState(.6),[spread,setSpread]=useState(1),[sensitivity,setSensitivity]=useState(1.5),[paused,setPaused]=useState(false),[camera,setCamera]=useState(false),[starting,setStarting]=useState(false),[status,setStatus]=useState('Move your pointer to explore'),[ready,setReady]=useState(false),[prompt,setPrompt]=useState('Iridescent liquid chrome, luminous lime aurora, deep black background, abstract flowing silk'),[key,setKey]=useState(''),[busy,setBusy]=useState(false),[genStatus,setGenStatus]=useState(''),[texture,setTexture]=useState(''),[clip,setClip]=useState('');
 const backdrop=useRef<HTMLVideoElement>(null);
 useEffect(()=>{const v=backdrop.current;if(!v)return;const sync=()=>{if(paused||document.hidden)v.pause();else void v.play().catch(()=>setGenStatus('Video playback paused. Use Play to retry.'));};sync();document.addEventListener('visibilitychange',sync);return()=>document.removeEventListener('visibilitychange',sync)},[paused,clip]);
 useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)setPaused(true)},[]);
 useEffect(()=>{state.current={preset,speed,spread,sensitivity,paused}},[preset,speed,spread,sensitivity,paused]);
 useEffect(()=>{let dead=false;let dispose=()=>{};
 (async()=>{try{const url='https://esm.sh/three@0.185.0';const T=await import(/* @vite-ignore */ url);if(dead)return;
 const engine=createScene(T,host.current!,input,state);api.current=engine;setReady(true);dispose=()=>{engine.dispose();api.current=null;};
 }catch(e){setStatus('3D could not load. Check your connection and WebGL support.')}})();
 return()=>{dead=true;dispose();generation.current++;cancelAnimationFrame(trackFrame.current);stream.current?.getTracks().forEach(t=>t.stop());tracker.current?.close()};},[]);
 function stopCamera(){lastNose.current=null;input.current={x:0,y:0};generation.current++;cancelAnimationFrame(trackFrame.current);stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;tracker.current?.close();tracker.current=null;setCamera(false);setStarting(false);setStatus('Move your pointer to explore');}
 async function startCamera(){if(camera){stopCamera();return}setStarting(true);setStatus('Loading face tracking…');const id=++generation.current;try{
 const url='https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.21/vision_bundle.mjs';const {FaceLandmarker,FilesetResolver}=await import(/* @vite-ignore */ url);
 const files=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.21/wasm');const landmarker=await FaceLandmarker.createFromOptions(files,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task',delegate:'CPU'},runningMode:'VIDEO',numFaces:1});
 if(id!==generation.current){landmarker.close();return}tracker.current=landmarker;
 const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:640,height:480},audio:false});if(id!==generation.current){media.getTracks().forEach(t=>t.stop());return}stream.current=media;video.current!.srcObject=media;await video.current!.play();setCamera(true);setStarting(false);let last=0,hadFace=false;
 const tick=(now:number)=>{if(id!==generation.current)return;try{if(!document.hidden&&now-last>65&&video.current?.readyState===4){last=now;const result=landmarker.detectForVideo(video.current,now);const nose=result.faceLandmarks[0]?.[1];if(nose){lastNose.current=nose;input.current=faceInput(nose,center.current);if(!hadFace)setStatus('Nose tracking active · move your head');hadFace=true;}else{lastNose.current=null;input.current={x:0,y:0};if(hadFace||last===now)setStatus('Find your face in the camera');hadFace=false;}}trackFrame.current=requestAnimationFrame(tick)}catch{stopCamera();setStatus('Tracking interrupted. Try enabling the camera again.')}};trackFrame.current=requestAnimationFrame(tick);
 }catch(e){stopCamera();setStatus('Camera unavailable. Allow camera access, or use your pointer.')}}
 function recenter(){if(lastNose.current)center.current={...lastNose.current};input.current={x:0,y:0};}
 async function generate(asVideo=false){if(!key.trim()){setGenStatus('Enter your own fal API key to generate.');return}setBusy(true);setGenStatus(asVideo?'Animating your atmosphere…':'Generating your atmosphere…');try{
 const headers={'Authorization':`Key ${key.trim()}`,'Content-Type':'application/json'};
 const res=await fetch(asVideo?'https://queue.fal.run/minimax/h3-max-turbo/image-to-video':'https://queue.fal.run/fal-ai/flux/schnell',{method:'POST',headers,body:JSON.stringify(asVideo?{prompt,image_url:texture,duration:5,resolution:'768P',prompt_expansion_mode:'balanced'}:{prompt,image_size:'landscape_16_9',num_images:1})});if(!res.ok)throw Error(`fal request failed (${res.status}). Check your key and credits.`);const job=await res.json();
 const statusUrl=safeFalUrl(job.status_url),responseUrl=safeFalUrl(job.response_url);let done=false;for(let n=0;n<90;n++){await new Promise(r=>setTimeout(r,2000));const sr=await fetch(statusUrl,{headers});if(!sr.ok)throw Error('Could not check generation status.');const st=await sr.json();if(st.status==='COMPLETED'){if(st.error)throw Error(String(st.error));done=true;break}if(st.status==='IN_QUEUE')setGenStatus('In the fal queue…');}if(!done)throw Error('Generation is taking longer than expected. Check your fal dashboard.');
 const rr=await fetch(responseUrl,{headers});if(!rr.ok)throw Error('Generation failed. Check your fal dashboard.');const result=await rr.json();const url=asVideo?result.video?.url:result.images?.[0]?.url;if(!url)throw Error('No media returned. Try another prompt.');if(asVideo)setClip(url);else{setTexture(url);setClip('');}setGenStatus('Atmosphere applied');
 }catch(e){setGenStatus(e instanceof Error?e.message:'Generation failed.')}finally{setBusy(false)}}
 function save(){if(!api.current)return;const a=document.createElement('a');a.download='noseflow-'+presets[preset].name.toLowerCase().replaceAll(' ','-')+'.png';a.href=api.current.renderer.domElement.toDataURL('image/png');a.click();}
 return <main><header><a className="brand" href="./">n<span>✳</span>seflow<span className="version">LIGHTFIELD / V.02</span></a><a className="credit" href="https://github.com/hanishkeloth/noseflow" target="_blank" rel="noreferrer">By Hanish Keloth <ArrowUpRight size={16}/></a></header>
 <div className="workspace"><section className="stage" tabIndex={0} aria-label="Interactive canvas. Use arrow keys to move, R to recenter." onKeyDown={e=>{if(camera)return;const moves:Record<string,number[]>={ArrowLeft:[-.1,0],ArrowRight:[.1,0],ArrowUp:[0,.1],ArrowDown:[0,-.1]};if(moves[e.key]){e.preventDefault();input.current={x:clamp(input.current.x+moves[e.key][0]),y:clamp(input.current.y+moves[e.key][1])};}if(e.key.toLowerCase()==="r")recenter();}} onPointerMove={e=>{if(!camera){const r=e.currentTarget.getBoundingClientRect();input.current={x:(e.clientX-r.left)/r.width*2-1,y:1-(e.clientY-r.top)/r.height*2}}}}>
 {clip&&<video ref={backdrop} className="atmosphere" src={clip} muted loop playsInline onError={()=>{setClip('');setGenStatus('Video could not load. Keeping the still image.');}}/>}{texture&&!clip&&<img className="atmosphere" src={texture} alt="AI-generated atmosphere"/>}<div className="stage-heading"><span className="eyebrow">AN EXPERIMENT IN HUMAN MOTION</span><h1>Make a move.<br/><em>Feel the flow.</em></h1><p>A living canvas, following your lead.</p></div><div className="canvas" ref={host}/><div className="scene-label"><span className="dot"/>{presets[preset].name}<span>{preset===3?'SPATIAL RIBBONS':'18K PARTICLES'}</span></div>
 <div className="stage-bottom"><span><MousePointer2 size={15}/>{status}</span><div><button aria-label="Recenter motion" onClick={recenter}><RotateCcw size={18}/></button><button aria-label={paused?'Play animation':'Pause animation'} onClick={()=>setPaused(!paused)}>{paused?<Play size={18}/>:<Pause size={18}/>}</button><button aria-label="Download particle canvas as PNG" disabled={!ready} onClick={save}><Download size={18}/></button></div></div></section>
 <aside><div className="panel-title"><span>THE CONTROLS</span><span>↗</span></div><section className="control-section"><div className="label-row"><h2>Choose a feeling</h2><span>01</span></div><div className="presets">{presets.map((p,i)=><button aria-pressed={preset===i} className={'preset '+(i===preset?'active':'')} key={p.name} onClick={()=>setPreset(i)}><span className={'swatch swatch-'+i}/><span><small>{p.tag}</small><strong>{p.name}</strong></span><span className="radio"/></button>)}</div></section>
 <section className="control-section"><div className="label-row"><h2>Shape the motion</h2><span>02</span></div>{[{name:'Flow speed',value:speed,set:setSpeed,min:.1,max:1.5},{name:'Expansion',value:spread,set:setSpread,min:.6,max:1.5},{name:'Sensitivity',value:sensitivity,set:setSensitivity,min:.5,max:3}].map(c=><div className="range" key={c.name}><div><label>{c.name}</label><span>{c.value.toFixed(1)}×</span></div><Slider aria-label={c.name} min={c.min} max={c.max} step={.1} value={[c.value]} onValueChange={v=>c.set(v[0])}/></div>)}</section>
 <section className="control-section"><div className="label-row"><h2>Your face is the controller</h2><ScanFace size={19}/></div><p>Move your nose. The world moves with you. Camera frames stay on your device.</p><video ref={video} muted playsInline className={camera?'camera':'camera hidden'}/><button className="camera-button" onClick={startCamera} disabled={starting}><Camera size={17}/>{starting?'Loading camera…':camera?'Turn camera off':'Enable nose tracking'}<ArrowUpRight size={16}/></button></section>
 <section className="control-section ai"><div className="label-row"><h2><Sparkles size={17}/> Dream a backdrop</h2><span className="fal">fal</span></div><textarea aria-label="Atmosphere prompt" value={prompt} onChange={e=>setPrompt(e.target.value)} maxLength={1500}/><input aria-label="Your fal API key" type="password" autoComplete="off" placeholder="Your fal API key" value={key} onChange={e=>setKey(e.target.value)}/><p className="note">Uses your fal credits. Key stays in memory and is sent only to fal. Video generation sends the generated still to fal. Camera images are never sent.</p><button className="generate" onClick={()=>generate()} disabled={busy||!prompt.trim()}><Sparkles size={16}/>{busy?'Dreaming…':'Generate atmosphere'}<ArrowUpRight size={16}/></button><button className="camera-button video-generate" onClick={()=>generate(true)} disabled={busy||!texture||!key.trim()}>Animate backdrop · 5 seconds</button><p className="note">Optional video uses additional fal credits. <a href="https://fal.ai/models/minimax/h3-max-turbo/image-to-video" target="_blank" rel="noreferrer">Check current pricing</a> before generating.</p><p role="status" className="note">{genStatus}</p>{texture&&<button className="clear" onClick={()=>{setTexture('');setClip('');}}><RotateCcw size={13}/>Clear atmosphere</button>}</section></aside></div>
 <footer><span>BUILT TO BE REMIXED.</span><span>THREE.JS × MEDIAPIPE × FAL</span><span>Less scrolling. More feeling.</span></footer></main>
}
